import type { Subscription } from './types'

export const seedSubs: Subscription[] = [
  {
    id: 'sub-netflix',
    name: 'Netflix',
    icon: '▶',
    color: '#FF3A30',
    price: 649,
    cardLast4: '0977',
    billingDate: '2025-05-12',
    status: 'active',
    category: 'Entertainment',
  },
  {
    id: 'sub-spotify',
    name: 'Spotify',
    icon: '♪',
    color: '#1DB954',
    price: 179,
    cardLast4: '1142',
    billingDate: '2025-05-01',
    status: 'active',
    category: 'Music',
  },
  {
    id: 'sub-claude',
    name: 'Claude',
    icon: '✳',
    color: '#7B6EF6',
    price: 1700,
    cardLast4: '0977',
    billingDate: '2025-05-23',
    status: 'active',
    category: 'AI',
  },
  {
    id: 'sub-chatgpt',
    name: 'ChatGPT',
    icon: 'AI',
    color: '#10A37F',
    price: 1650,
    cardLast4: '0977',
    billingDate: '2025-06-15',
    status: 'active',
    category: 'AI',
  },
  {
    id: 'sub-youtube',
    name: 'YouTube Premium',
    icon: '▷',
    color: '#FF0000',
    price: 189,
    cardLast4: '1142',
    billingDate: '2025-05-18',
    status: 'active',
    category: 'Entertainment',
  },
  {
    id: 'sub-ms365',
    name: 'Microsoft 365',
    icon: 'M',
    color: '#0078D4',
    price: 830,
    cardLast4: '0977',
    billingDate: '2025-01-01',
    status: 'expired',
    category: 'Productivity',
  },
]
