import type { Subscription } from './types'

// INR monthly prices. 12 active + 1 expired matches the "12+ active subscription" caption.
export const seedSubs: Subscription[] = [
  {
    id: 'sub-claude',
    name: 'Claude',
    icon: '✳',
    color: '#D97757',
    price: 1700,
    cardLast4: '0977',
    billingDate: '2025-03-12',
    status: 'active',
    category: 'AI',
  },
  {
    id: 'sub-netflix',
    name: 'Netflix',
    icon: 'N',
    color: '#E50914',
    price: 649,
    cardLast4: '0977',
    billingDate: '2025-12-23',
    status: 'active',
    category: 'Entertainment',
  },
  {
    id: 'sub-chatgpt',
    name: 'ChatGPT',
    icon: 'AI',
    color: '#10A37F',
    price: 1650,
    cardLast4: '0977',
    billingDate: '2025-06-15',
    status: 'active',
    category: 'AI',
  },
  {
    id: 'sub-youtube',
    name: 'YouTube Premium',
    icon: '▷',
    color: '#FF0000',
    price: 189,
    cardLast4: '1142',
    billingDate: '2025-05-18',
    status: 'active',
    category: 'Entertainment',
  },
  {
    id: 'sub-spotify',
    name: 'Spotify',
    icon: '♪',
    color: '#1DB954',
    price: 179,
    cardLast4: '1142',
    billingDate: '2025-05-01',
    status: 'active',
    category: 'Music',
  },
  {
    id: 'sub-adobe',
    name: 'Adobe CC',
    icon: 'A',
    color: '#FA0F00',
    price: 4229,
    cardLast4: '0977',
    billingDate: '2025-07-02',
    status: 'active',
    category: 'Design',
  },
  {
    id: 'sub-figma',
    name: 'Figma',
    icon: 'F',
    color: '#F24E1E',
    price: 999,
    cardLast4: '0977',
    billingDate: '2025-08-14',
    status: 'active',
    category: 'Design',
  },
  {
    id: 'sub-notion',
    name: 'Notion',
    icon: 'N',
    color: '#111111',
    price: 660,
    cardLast4: '1142',
    billingDate: '2025-05-30',
    status: 'active',
    category: 'Productivity',
  },
  {
    id: 'sub-discord',
    name: 'Discord Nitro',
    icon: 'D',
    color: '#5865F2',
    price: 830,
    cardLast4: '1142',
    billingDate: '2025-06-04',
    status: 'active',
    category: 'Social',
  },
  {
    id: 'sub-appleone',
    name: 'Apple One',
    icon: '',
    color: '#111111',
    price: 1499,
    cardLast4: '0977',
    billingDate: '2025-05-08',
    status: 'active',
    category: 'Productivity',
  },
  {
    id: 'sub-icloud',
    name: 'iCloud+',
    icon: '☁',
    color: '#3B82F6',
    price: 219,
    cardLast4: '0977',
    billingDate: '2025-05-25',
    status: 'active',
    category: 'Storage',
  },
  {
    id: 'sub-github',
    name: 'GitHub Pro',
    icon: 'G',
    color: '#111111',
    price: 330,
    cardLast4: '0977',
    billingDate: '2025-06-11',
    status: 'active',
    category: 'Dev',
  },
  {
    id: 'sub-ms365',
    name: 'Microsoft 365',
    icon: 'M',
    color: '#0078D4',
    price: 830,
    cardLast4: '0977',
    billingDate: '2025-01-01',
    status: 'expired',
    category: 'Productivity',
  },
]
